### ISSUE TITLE
在集成 react-native-wechat-lib 之后，Android 编译报错：Program type already present: com.alipay.a.a.e

### ISSUE THREAD

**Issue by Riant** [uiwjs/react-native-alipay#29]
集成 react-native-wechat-lib 之前没有问题，但是之后，Android 编译就报错了：

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
     Program type already present: com.alipay.a.a.e
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```

看了下 alipay 的 sdk jar 文件里边确实有 com.alipay.a.a.e 这个类，请问下，是什么原因，有什么办法解决吗？
谢谢。

**Comment by asagcs** [comment]
同问++1  解决了么 @Riant

**Comment by Leo2018Wu** [comment]
> 同问++1 解决了么 @Riant

加问

**Comment by Leo2018Wu** [comment]
把libs文件夹里面的sdk替换成兼容版的不报错
![image](https://user-images.githubusercontent.com/43198067/111288308-03580200-867f-11eb-9712-91ad0690e120.png)

**Comment by Riant** [comment]
@asagcs  @Leo2018Wu  
我之前以为 alipay 不会自定 linking, 所以作了手动 linking, 然后可能与其他手动 linking 的库冲突了，我当时是通过调整 android/app/build.gradle 里边的几个 implementation 的顺序解决的。

我现在移除了 alipay 的手动 linking 代码了，没出现这个问题了。当然，我还有一些库是不支持 auto linking 的，需要手动 linking, 也还是遇到了类似的问题，只不过冲突的是其他 class 而已，依然是通过调整 implementation 的顺序解决的。

注意在调整顺序之后，删除 build 文件夹里边的 generated 和 intermediates 2个文件夹再尝试编译。
