### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR. 

### ISSUE THREAD

**Issue by meiqi1992** [uiwjs/react-native-alipay#32]
he resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar

**Comment by meiqi1992** [comment]
升级 gradle 4.0.1

**Comment by Riant** [comment]
#18

**Comment by jaywcjlove** [comment]
#18
