### ISSUE TITLE
支付后回调函数没有执行

### ISSUE THREAD

**Issue by zhaokgithub** [uiwjs/react-native-alipay#33]
支付宝支付成功后回到商家app但是没有执行到回调函数中（ios端）

Alipay.alipay(payInfo, (res) => {
                console.log('00000000000', res)
            });

**Comment by jaywcjlove** [comment]
@zhaokgithub 

> `Alipay.alipay: (payInfo: string) => Promise<OrderResult>;`

- ⚠️ 注意支付成功返回结果是一个字符串，[返回内容](https://github.com/uiwjs/react-native-alipay/blob/74140a294e850884ed1851b9d2c2d2c00ee75003/index.d.ts#L50-L74)  
- ⚠️ 支付宝需要设置 `Scheme` 和 iOS添加原生代码，才能支持支付和[回弹商家APP](#支付宝返回应用-ios-设置)的功能
- ⚠️ 支付宝 `管理中心-支付宝开放平台` 需要签约 [`APP支付`](https://opendocs.alipay.com/open/200/105310#%E6%B7%BB%E5%8A%A0%E5%BA%94%E7%94%A8%E5%8A%9F%E8%83%BD)

**Comment by zhaokgithub** [comment]
> @zhaokgithub
> 
> > `Alipay.alipay: (payInfo: string) => Promise<OrderResult>;`
> 
> * ⚠️ 注意支付成功返回结果是一个字符串，[返回内容](https://github.com/uiwjs/react-native-alipay/blob/74140a294e850884ed1851b9d2c2d2c00ee75003/index.d.ts#L50-L74)
> * ⚠️ 支付宝需要设置 `Scheme` 和 iOS添加原生代码，才能支持支付和[回弹商家APP](#%E6%94%AF%E4%BB%98%E5%AE%9D%E8%BF%94%E5%9B%9E%E5%BA%94%E7%94%A8-ios-%E8%AE%BE%E7%BD%AE)的功能
> * ⚠️ 支付宝 `管理中心-支付宝开放平台` 需要签约 [`APP支付`](https://opendocs.alipay.com/open/200/105310#%E6%B7%BB%E5%8A%A0%E5%BA%94%E7%94%A8%E5%8A%9F%E8%83%BD)

我是这样做的 android是正常的 ios不行

**Comment by zhaokgithub** [comment]
已经处理 ios原生代码引入不正确
