### ISSUE TITLE
ios 手机没有安装支付宝，无法调起网页支付

### ISSUE THREAD

**Issue by jameszhan02** [uiwjs/react-native-alipay#52]

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/148149715-e83a7b37-1c9d-422d-b56c-d65e3b503ae3.png)

@jameszhan02 你需要自主诊断一下 :)

**Comment by jameszhan02** [comment]
好的好的，谢谢谢谢

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
